%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1       
num_of_cam: 2

#imu_topic: "/imu0"
#image0_topic: "/cam0/image_raw"
#image1_topic: "/cam1/image_raw"

imu_topic: "/IMU_data"
image0_topic: "/camera/left/image_raw"
image1_topic: "/camera/right/image_raw"
#image0_topic: "/l"
#image1_topic: "/r"
output_path: "/home/rvl/vinsfusion_ws/src/VINS-Fusion/output/"

cam0_calib: "nav_left.yaml"
cam1_calib: "nav_right.yaml"
image_width: 1280
image_height: 720
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data:  [-0.9995667,  -0.02942426,  0.00078988, -0.16897755,
           -0.0294122,   0.99949029,  0.01241265, -0.03628774,
           -0.00115471,  0.01238404, -0.99992265, -0.07822009,
           0.        ,  0.       ,   0.     ,     1.        ]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data:  [-0.9988116,  -0.04828526,  0.00662725,  0.09390498,
           -0.04825065,  0.99882127,  0.00528689, -0.03720595,
           -0.00687472,  0.00496084, -0.99996406, -0.07770981,
          0.      ,    0.   ,       0.      ,    1.        ]
#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 200   # max feature number in feature tracking150
min_dist: 35         # min distance between two features 30
freq: 10            # frequence (Hz) of publish tracking result. At least 10Hz10 for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time0.04
max_num_iterations: 8   # max solver itrations, to guarantee real time8
keyframe_parallax: 10 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
#acc_n: 8.6736600335954785e-03        # accelerometer measurement noise standard deviation. 
#gyr_n: 3.9773992766546666e-03      # gyroscope measurement noise standard deviation.     
#acc_w: 4.8765014444383461e-04       # accelerometer bias random work noise standard deviation.  
#gyr_w: 1.7201506819560241e-05     # gyroscope bias random work noise standard deviation.
acc_n: 6.8167160324812013e-03        # accelerometer measurement noise standard deviation. 
gyr_n: 1.7596628205489139e-03      # gyroscope measurement noise standard deviation.     
acc_w: 2.3456129820665947e-04       # accelerometer bias random work noise standard deviation.  
gyr_w: 9.8125320783399806e-06     # gyroscope bias random work noise standard deviation.     
g_norm: 9.7949     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                    # online estimate time offset between camera and imu
td: 0.0                           # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0       # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/rvl/vinsfusion_ws/src/VINS-Fusion/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
